## ENSO and climate change and opportunities for restoration and sustainable agrarian management

Climate change will most likely increase the frequency and intensity of El Niño events [@cai_increasing_2014; @IPCC.2014; @wang_continued_2017].
This and climate change in general pose the risk to turn tropical forests - dry and moist - from carbon sinks to sources [@phillips_changes_2009; @salazar_tree_accepted]. 
This is also true for the study area [@salazar_tree_accepted] where EN is frequently associated with higher rainfall and LN with increased aridity.
However, both can also cause the opposite effects. 
For instance, 2005 was a very dry EN year, 2012 was a humid LN year, and 2017 was first predicted to be a LN year and then turned out to be a very wet neutral year (coastal EN; see Fig. \@ref(fig:study-area-map)d for many more examples). 
Hence, deviations from the mean expectation were the norm for the study area in the last two decades.
However, this is only true when solely relying on the popular ONI index -- an index, which measures sea surface temperature anomalies in the central Pacific. 
Naturally, local anomalies possibly overlap, dilute and modify the ENSO signal stemming from the central Pacific. 
Studies have shown that indices computed from the EN region 1+2, which corresponds to an area in the tropical Pacific close to the South American coast, already provide better correlations with climate anomalies in northern Peru and southern Ecuador [@kao_contrasting_2009;@salazar_effect_2018]. 
At least two further local indexes seem to be also promising for predicting climate anomalies along the Peruvian coast.
The first is the Índice Costero El Niño (ICEN; see http://www.met.igp.gob.pe/publicaciones/2014/ElNino_v2_27_03_2014_7.pdf), and the second is an ENSO index for the insurance of agricultural products [@mortensen_enso_2018].

In any case, constant monitoring is a prerequisite for a better understanding of ENSO-affected ecosystems. 
Since ENSO exerts its most direct influence on tropical regions, and all corresponding ecosystems are endangered without exception, the correct prediction of the expected ENSO effects are a cornerstone of informed conservation and reforestation management. 
Conserving and reversing the state of degraded ecosystems also helps to mitigate the effects of floodings and landslides due to excessive rainfalls, and thereby contributes to protect the population and infrastructure from unnecessary harm [@fraser_peru_2017; @ramirez_understanding_2017].
Currently, the regional government has set up eleven restoration projects in northern Peru which are trying to protect the endemic vegetation and increase vegetation cover through reforestation.
Additionally, NGOs and mining companies are also working on reforestation projects.
Most of these projects rely on extreme events (like 2017 EN) to boost plant growth to overcome the otherwise very limited access to water.
Our experimental results indicated that water availability showed a non-linear relationship with biodiversity and plant cover.
Therefore, restoration projects might consider water regulation in combination with a sensible amount of fertilization [@dahlsjo_local_2019].
The same applies to a sustainable agrarian management.
Indeed, agricultural development has been very intense over the last 20 years in the study area.
Personal communications with the main local companies indicated that extreme events are an important issue.
On the one hand, El Niño has the potential to boost crop productivity.
On the other hand, especially short and very intense rainfall might create havoc during the crop season as was the case during the 2017 EN.
Our results show the spatial variability of biomass production in response to water availability along the climatic gradient, which might be also an important information for agrarian activities.

## Conclusions

## Title

Monitoring and predictive mapping of floristic biodiversity along a climatic gradient across four years in ENSO's terrestrial core region, NW Peru

along a spatio-temporal gradient

relationship with environmental variables

machine learning, statistical learning, variation partitioning, DCA (ordination)